@startuml
actor User as User
participant "commands\nrun" as RunCommand
participant "libcontainer\nrun" as Run
participant "libcontainer\ncreate" as Create
participant "libcontainer\nruntime" as Runtime
participant "libcontainer\nfilesystem" as Filesystem
participant "libcontainer\nstate.ContainerState" as ContainerState
participant "libcontainer\nstart" as Start
participant "libcontianer\nsched" as Sched
participant "oci_runtime\nSpec" as OCISpec
participant "\nPosix" as Posix
participant "OS\nlinux" as Linux

User -> RunCommand: exec
activate RunCommand #FFBBBB

RunCommand -> Run: runContainer(rootDir, opts)
activate Run #Salmon

Run -> Create: createContainer(rootDir, opts)
activate Create #Salmon

Create -> Filesystem: initRootPath(rootDir, name)
activate Filesystem #Salmon

Filesystem --> Create: runtime (basePath)
deactivate Filesystem

Create -> OCISpec: initFromFile(file)
activate OCISpec #Salmon

OCISpec --> Create: Spec
deactivate OCISpec

Create -> ContainerState: init(rootDir, bundleDir, rootfs, spec, noPivot)\nwriteStateFile()
activate ContainerState #Salmon

ContainerState --> Create: cntstate
deactivate ContainerState

Create --> Run:
deactivate Create

Run -> Start: startContainer(rootDir, name)
activate Start #Salmon

Start -> Filesystem: initRootPath(rootDir, name): initRootPath(rootDir, name)
activate Filesystem #Salmon

Filesystem --> Start: runtime (basePath)
deactivate Filesystem

Start -> ContainerState: initFromFile(rootDir)
activate ContainerState #Salmon

ContainerState --> Start: cntstate
deactivate ContainerState

Start -> OCISpec: initFromFile(specFile)
activate OCISpec #LightGray

OCISpec --> Start: runtimeSpec
deactivate OCISpec

Start -> Sched: clone
activate Sched #Salmon

Sched -> Runtime: prepareAndExecute(rootfs, spec, noPivot)
activate Sched #DarkSalmon
activate Runtime #Salmon
Runtime -> Runtime: containerSetHostname(hostname)
Runtime -> Runtime: containerSetDomainname(domainname)
Runtime -> Runtime: setChroot/PivotRootFS(rootfs)
Runtime -> Runtime: containerSetCwd(process.cwd)
Runtime -> Runtime: containerSetMountPoints()
Runtime -> Runtime: containerSetMountPoints()
Runtime -> Linux: execve
activate Linux #LightGray
Linux --> Runtime
deactivate Linux
Runtime --> Sched
deactivate Runtime
deactivate Sched


Sched --> Start: childPID
deactivate Sched

Start -> Posix: init(waitPID(childPID))
activate Posix #LightGray

Posix --> Start: success/error
deactivate Posix

Start -> Run:
deactivate Start

Run --> RunCommand:
deactivate Run

RunCommand --> User:
deactivate RunCommand

@enduml
