name: build
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1

  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          skip: ./.git,./vendor,*_test.go,go.sum,go.mod

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - run: |
          make build

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - run: |
          make fmt

  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - run: |
          sudo apt-get install binutils-dev libssl-dev libcurl4-openssl-dev libelf-dev libstdc++-12-dev zlib1g-dev libdw-dev libiberty-dev git
          git clone https://github.com/SimonKagstrom/kcov.git
          cd kcov
          git checkout v43
          mkdir build
          cd build
          cmake ..
          make
          sudo make install
      - run: |
          make test
      #    make coverage

      #- name: Upload coverage reports to Codecov
      #  uses: codecov/codecov-action@v3
      #  with:
      #    file: .coverage/test/cov.xml
      #    token: ${{ secrets.CODECOV_TOKEN }}
      #    name: codecov-umbrella
      #    fail_ci_if_error: true
